### PR TITLE
Render Ks signals regardless of their displayable signal states

### PR DESCRIPTION
**Pull request by Nakaner**
This enables rendering of Ks main and combined signals which can display a marker light and implements a change of tagging of marker lights a few months ago. This fixes a bug.

### CODE REVIEW

**Comment by PeterDRS** [comment]
Why is ["railway:signal:distant:form"=light] a criteria for rendering?

Why are semaphore Ks signals not rendered?

**Comment by DerDakon** [comment]
Because there are no semaphore Ks signals.

**Comment by rurseekatze** [comment]
> Why are semaphore Ks signals not rendered?

Good joke... :smile:

**Comment by PeterDRS** [comment]
Thanks for your information.

When there are no semaphore Ks signals, why tagging that it is a light signal.

And why not rendering Ks signals without the form tag?

**Comment by DerDakon** [comment]
This is just a QA thing, the same as the direction tag.

**Comment by PeterDRS** [comment]
It is unneccessary and should be removed.

You won't tag a post box of Deutsche Post with color:yellow.

**Comment by Nakaner** [comment]
This pull request is in conflict with pull request #260. Because we should support good tagging, I close this pull request.

**Pull request closed without merging**
