### PR TITLE
Minor josm preset fix

### PR DESCRIPTION
**Pull request by sb12**

### CODE REVIEW

**Comment by Nakaner** [comment]
:+1: I support a quick merge.

@sb12 Will you do the fixing edti at OSM which repairs the "damage" caused by this preset bug? Overpass API [says](http://overpass-turbo.eu/s/c0A) that 72 objects in Germany are affect. Those in East and most of the objects in Southern Germany have been added by myself.

**Comment by sb12** [comment]
I will "fix" the "damage" after the PR has been merged.

**Comment by sb12** [comment]
http://www.openstreetmap.org/changeset/34664758 (2 of the 72 were already corrected by myself, when I found the bug)

**Comment by rurseekatze** [comment]
:+1: Overpass does not find broken signals anymore.

**Pull request merged**
