### PR TITLE
signals: show German Ks signals if they have additional states

### PR DESCRIPTION
**Pull request by DerDakon**
Allow either "off" or "DE-ESO:kennlicht" as additional states.

### CODE REVIEW

**Comment by DerDakon** [comment]
Either merge this one or #273.

**Comment by DerDakon** [comment]
This only works in JOSM if you have at least version 8535 because of [JOSM bug 11598](https://josm.openstreetmap.de/ticket/11598).

**Comment by rurseekatze** [comment]
I think that the problem also occurs at Ks combined signals. Can you also fix that issue for these signals?

**Comment by DerDakon** [comment]
Done for both combined and distant signals, and it allows now multiple of the additional states to be present.

**Pull request merged**
