### PR TITLE
Fix rendering of incompletely tagged Hp light and semaphore signals

### PR DESCRIPTION
**Pull request by Nakaner**
This fixes issue #194.

### CODE REVIEW

**Comment by DerDakon** [comment]
The first and third rule can be simplified to ...!~/.*hp[12].*/]

**Comment by Nakaner** [comment]
I have [simplified some regular expressions](https://github.com/Nakaner/OpenRailwayMap/commit/97cb80b3baa8c619ccd78e1c2efeda67ae2b8e61).

**Comment by rurseekatze** [comment]
I reverted the merge because the changes produced syntax errors in MapCSS converter. See https://github.com/rurseekatze/OpenRailwayMap/commit/07dd865e7fb1c18a670799ec039f778c9e76dcea for further details.

**Comment by rurseekatze** [comment]
@Dakon reintroduced some code in https://github.com/rurseekatze/OpenRailwayMap/pull/225.

**Pull request merged**
