### PR TITLE
show proposed and constructed tracks only when the finished tracks would be shown

### PR DESCRIPTION
**Pull request by DerDakon**
Otherwise e.g. proposed tram lines would be shown on level 9, but tram lines only on level 11.

### CODE REVIEW

**Comment by sb12** [comment]
Same problem applies to abandoned, disused and razed tram lines. Maybe you could apply the same change to these as well.

Good test location is [Karlsruhe](http://www.openrailwaymap.org/?lang=en&lat=49.009501205463394&lon=8.581008911132812&zoom=10&style=standard) where you have abandoned, disused, razed, proposed and constructed tram lines.

**Comment by DerDakon** [comment]
Working on it. This needs to be done for bridges and tunnels, too, so this becomes a bit messy.

**Comment by DerDakon** [comment]
This will only be fixed if [#67 in node-tileserver](https://github.com/rurseekatze/node-tileserver/pull/67) will be merged first as it get's unnecessarily messy otherwise.

**Comment by DerDakon** [comment]
This need #399 to work.

**Pull request closed without merging**
