### PR TITLE
Issue 171 catenary signals

### LINKED ISSUE #171: Add German/Austrian catenary signals
Add following German catenary signals (El). They are also used in Austria but have different names there:

* El 1
* El 1v
* El 2
* El 3
* El 4
* El 5
* El 6
* direction arrow used on El signals

### PR DESCRIPTION
**Pull request by Nakaner**
This pull requests adds
* German signals El 1, El 1v, El 2, … El 6
* right and left direction arrows used on El 6 signs
* Austrian equivalents of the signs called above

This fixes #171

### CODE REVIEW

**Comment by JJJWegdam** [comment]
I propose to merge this with [#124](https://github.com/rurseekatze/OpenRailwayMap/issues/124).

**Comment by Nakaner** [comment]
I agree @DerDakon that we should render catenary signals only at the electrification layer (canvas-based map only) to reduce the "noise" at signal layer.

@DerDakon You can move the whole code to the branch electricity-layer in your fork and create a pull request afterwards. As @rurseekatze said, it is not possible to serve it as raster tiles (due to hardware restrictions) but the layer can be used for mapping in JOSM and at our [canvas variant](http://www.openrailwaymap.org/canvas.php).

**Comment by DerDakon** [comment]
I have updated my branch. Please check if I have transferred everything correctly. Afterwards remove the changes in signals.mapcss from your branch and squash everything together.

**Comment by Nakaner** [comment]
I hereby close this pull request because it has been replaced by pull request #221 which fixes the same issue in a better way.

**Pull request closed without merging**
