### PR TITLE
Electricity layer

### PR DESCRIPTION
**Pull request by DerDakon**
Implements #171 and parts of #124.

### CODE REVIEW

**Comment by DerDakon** [comment]
Needs [#57 in node-tileserver](https://github.com/rurseekatze/node-tileserver/pull/57) to work.

**Comment by Nakaner** [comment]
Please merge this pull request (and its depending PR [#67](https://github.com/rurseekatze/node-tileserver/pull/67) in node-tileserver). I would like to use these icons for a JOSM preset.

Merging a PR does not mean that you have to deploy the style at the server.

**Comment by DerDakon** [comment]
If it makes a hassle I could split out the icon and JOSM part into a new PR.

**Comment by DerDakon** [comment]
Don't forget to update renderer/ before merging this.

**Pull request merged**
