### PR TITLE
Fix validator syntax

### PR DESCRIPTION
**Pull request by Nakaner**
"area" is an illegal object type. I replaced it by "relation".

This removes some exceptions JOSM throws.

### CODE REVIEW

**Comment by rurseekatze** [comment]
Why did you remove `area`? It is a valid selector: https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation#Selectors

I would suggest to keep `area` and add `relation`.

**Comment by DerDakon** [comment]
The errors come only from the "area" in asserts, the actual selectors are fine.

**Comment by DerDakon** [comment]
Just drop this one and update your JOSM: https://josm.openstreetmap.de/ticket/11370#comment:3

**Comment by rurseekatze** [comment]
Issue can be closed because there is nothing to do on our side.

I will add the check for `railway=station/crossing/level_crossing` mapped as relations in a separate commit.

**Comment by rurseekatze** [comment]
Nothing to do on our side, issue can be closed.

**Pull request closed without merging**
