### PR TITLE
style: replace deprecated "@media" by "@supports"

### PR DESCRIPTION
**Pull request by don-vip**
See https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation#Mediaqueriessince6970deprecated

### CODE REVIEW

**Comment by DerDakon** [comment]
This will not work until the mapcss parser in node-tileserver learns to support @supports.

**Comment by DerDakon** [comment]
As suggested by your own documentation you should also add "min-josm-version: "8087"; /* This style uses @supports rules */" to the header of the file.

**Comment by don-vip** [comment]
correct.

**Comment by stoecker** [comment]
Any progress? It's the last issue causing a test failure.

**Comment by DerDakon** [comment]
The code is in [my @supports-branch](https://github.com/DerDakon/node-tileserver/tree/%40supports), but not finished yet.

**Comment by DerDakon** [comment]
I would suggest 2 things:
 * squash those 2 commits together, because they logically belong together
 * invert the logic, so that the JOSM code lives inside the "@supports", the current form was only used because of the constrained "@media" implementation in node-tileserver.

**Comment by don-vip** [comment]
I'm not much a git guy. I tried to squeeze my commits and apparently messed up my branch. Can you please just close my PR and commmit what you think is the best? It will be faster than wait for me to understand how to git rebase properly.

**Comment by don-vip** [comment]
I'm unable to merge my commits, I have created #459, easier.

**Pull request closed without merging**
