### PR TITLE
Bugfix Zs 3v

### PR DESCRIPTION
**Pull request by PeterDRS**
Fix a bug in Zs 3v code.

### CODE REVIEW

**Comment by PeterDRS** [comment]
Nazi!

**Comment by rurseekatze** [comment]
Your strategy is simple to understand. You knew that I would never merge this attempted vandalism and would close the pull request.

**Comment by PeterDRS** [comment]
If I found real bugs, you merge it. You even do not say "thanks".

You are a fucking "Hurensohn", and I will do my own project.

**Comment by rurseekatze** [comment]
> If I found real bugs, you merge it.

Ohh, that is not nice. I better should close your bugfixes.

> You are a fucking "Hurensohn",...

I think that there is not anything to comment here. The used vocabulary reveals a lot about the author.

> ... and I will do my own project.

I am happy to see the first results!

**Pull request closed without merging**
